name: Build
on: push

jobs:
  build:
    name: Compile Scores
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup LilyPond
        uses: codello/setup-lilypond@main
        with:
          lilypond-version: "2.24"
          ol-fonts: beethoven
      - name: Install Yorkten Font
        run: aws s3 cp s3://brewery/fonts/yorkten/ "$HOME/.local/share/fonts" --recursive
        env:
          AWS_ENDPOINT_URL: https://s3.eu-central-003.backblazeb2.com
          AWS_DEFAULT_REGION: eu-central
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Compile Scores
        run: make all
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scores
          path: build/*
          